In [73]:
import numpy as np

import pandas as pd
df = pd.read_csv("/prouni2018.csv", index_col=0)
df.query('turno == "Curso a Distância"').head(5000)
#Query me indica os alunos correspondentes aos cursos EAD

            cidade_busca  ... nota_parcial_cotas
uf_busca                  ...
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...             586.62
RJ        Rio de Janeiro  ...                NaN
...                  ...  ...                ...
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN

[203 rows x 15 columns]

In [50]:
df.query('mensalidade <= 300').head(5000)
#Alunos que pagam a mensalidade inferior ou igual a 300 reais

            cidade_busca  ... nota_parcial_cotas
uf_busca                  ...
RJ        Rio de Janeiro  ...             586.62
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
...                  ...  ...                ...
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN

[100 rows x 15 columns]

In [66]:
df.groupby(by='turno').size()
#Analise quantitativa em relação aos turnos

turno
Curso a Distância    203
Integral              56
Matutino             121
Noturno              148
Vespertino             3
dtype: int64

In [79]:
df.groupby(['universidade_nome','nome','turno']).agg({'mensalidade': np.mean, 'cidade_busca':np.size}).head(5000)
#Analise da média do valor da mensalidade paga por Turno, Curso e Universidade

                                                                                                   mensalidade  cidade_busca
universidade_nome                              nome                             turno
Centro Universitário Celso Lisboa - Ucl - UCL  Biomedicina                      Matutino              1129.510             1
                                               Ciências Contábeis               Matutino               863.940             2
                                                                                Noturno                990.350             1
                                               Engenharia Ambiental e Sanitária Noturno               1190.030             1
                                               Engenharia Civil                 Noturno               1279.290             1
...                                                                                                        ...           ...
Universidade Veiga de Almeida - UVA            Relações Internacionais          Noturno               1399.585             2
                                               Serviço Social                   Matutino              1213.390             1
                                               Sistemas de Informação           Noturno               1198.440             1
                                               Turismo                          Matutino              1296.920             1
Universidade do Sul de Santa Catarina - UNISUL Ciências Aeronáuticas            Curso a Distância     1102.540             1

[418 rows x 2 columns]

In [84]:
df.groupby(by='nome').size()

nome
Administração                            42
Agronegócio                               1
Análise e Desenvolvimento de Sistemas    11
Arquitetura e Urbanismo                   7
Artes Cênicas                             1
                                         ..
Sistemas de Informação                    5
Sistemas para Internet                    1
Sociologia                                2
Teologia                                  7
Turismo                                   2
Length: 100, dtype: int64

In [91]:
df.query('nome == "Arquitetura e Urbanismo"').head(100)
#verificando os dados dos alunos do CURSO de arquitetura e urbanismo

            cidade_busca  ... nota_parcial_cotas
uf_busca                  ...
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN
RJ        Rio de Janeiro  ...                NaN

[7 rows x 15 columns]